language: objective-c
rvm: 2.0.0
before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - brew update
    - brew outdated xctool || brew upgrade xctool
    - cd Example
script: xctool -project GKActionSheetExample.xcodeproj -scheme GKActionSheetExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build